name: Deploy ECS Dev

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/ecs/dev/**'

jobs:
  terraform:      
    name: 'Terraform Init, Format, Validate, Plan, Apply'    
    runs-on: ubuntu-latest 

    env:
      AWS_REGION: 'ap-south-1'    
      TF_VERSION: '1.4.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Install Terragrunt
        run: |
         curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.56.3/terragrunt_linux_amd64
         chmod +x terragrunt
         sudo mv terragrunt /usr/local/bin/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terragrunt Init
        run: terragrunt init

      - name: Terragrunt Apply
        run: terragrunt apply -auto-approve
        