
name: Clear Terraform & Terragrunt Cache

on:
  push:
    paths:
      - '.github/workflows/destroy.yaml'
    branches:
      - main

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    env:
     AWS_REGION: 'ap-south-1'    
     TF_VERSION: '1.4.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run Terragrunt Init
        working-directory: infrastructure/ecs-cluster/dev
        run: terragrunt init


      - name: Destroy infrastructure with Terragrunt
        run: terragrunt destroy -auto-approve
        working-directory: infrastructure/ecs/dev