name: Terraform Dev Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/EC2/dev/**'
      - '.github/workflows/terraform-dev.yaml'

jobs:
  terraform:
    name: Terraform Init, Validate, Plan
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'ap-south-1'
      AWS_DEFAULT_REGION: 'ap-south-1'
      TF_VERSION: '1.4.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Remove cached Terraform modules
        run: rm -rf infrastructure/EC2/dev/.terraform/modules

      - name: Terraform Init
        run: terraform -chdir=infrastructure/EC2/dev init

      - name: Terraform Validate
        run: terraform -chdir=infrastructure/EC2/dev validate

      - name: Terraform Plan
        run: terraform -chdir=infrastructure/EC2/dev plan -out=tfplan -var-file=dev.tfvars
